development: &development
  plantuml:
    description: "Constructs UML diagram image from its textual description in PlantUML language, see http://plantuml.sourceforge.net"
    command: "/usr/bin/plantuml -pipe"
    content_type: "image/png"
    prolog: "@startuml"
    epilog: "@enduml"
  graphviz:
    description: "Constructs graph image from its textual description in DOT language, see http://www.graphviz.org"
    command: "/usr/bin/dot -Tsvg"
    content_type: "image/svg+xml"
  ritex:
    description: "Converts WebTeX expression to MathML, see http://ritex.rubyforge.org/"
    command: "(echo '<!DOCTYPE math PUBLIC \"-//W3C//DTD MathML 2.0//EN\" \"http://www.w3.org/Math/DTD/mathml2/mathml2.dtd\">'; /usr/bin/ritex) | xmllint --noent --nonet --catalogs --loaddtd - | sed 's/^<!DOCTYPE.\\+$//' | /usr/bin/math2svg"
    content_type: "image/svg+xml"
# For MathML-compliant browsers and when Redmine is fully XML-compliant.
#  ritex:
#    description: "Converts WebTeX expression to MathML, see http://ritex.rubyforge.org/"
#    command: "/usr/bin/ritex"
#    content_type: "application/xhtml+xml"
  fortune:
    description: "Prints a random, hopefully interesting, adage, see http://en.wikipedia.org/wiki/Fortune_(Unix)"
    command: "/usr/bin/fortune"
    cache_seconds: 0
    content_type: "text/plain"

test:
  type: mock

production:
  <<: *development
